import { sendEmail, getDailyStats } from '../src/mailer.js';

const outreach = [
  { to: 'hello@redbarnrobotics.com', company: 'Red Barn Robotics', body: `Hey,\n\nRed Barn Robotics is solving a real problem in ag-tech — and robotics is one of those products that looks 10x better in motion. I make short motion graphic brand videos for deep tech startups that make complex hardware instantly understandable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mentra.glass', company: 'Mentra', body: `Hey,\n\nMentra is building the open source OS for smart glasses — a genuinely new product category that's hard to explain in text. I make short motion graphic brand videos for hardware and AI startups that make new tech click instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@blindpay.com', company: 'BlindPay', body: `Hey,\n\nBlindPay caught my eye. Fintech infrastructure is notoriously hard to explain — a clean motion graphic explainer can do a lot of heavy lifting. I make short brand videos for fintech startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@vantel.ai', company: 'Vantel', body: `Hey,\n\nVantel is building AI for sales — a space where showing the product in action beats any written pitch. I make short motion graphic brand videos for AI startups that make the value click in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@firaresearch.com', company: 'Fira', body: `Hey,\n\nFira is doing interesting work in AI research. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@assistant-ui.com', company: 'assistant-ui', body: `Hey,\n\nassistant-ui is building UI components for AI chat — a dev-tools product that deserves a clean demo video. I make short motion graphic brand videos for AI and dev-tools startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@artifact.engineer', company: 'Artifact', body: `Hey,\n\nArtifact is building in AI engineering — a product that's technical but deserves a visual story. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@axal.ai', company: 'Axal', body: `Hey,\n\nAxal is doing interesting work in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@getdexterity.com', company: 'Dexterity', body: `Hey,\n\nDexterity is building in AI — a space where showing beats telling every time. I make short motion graphic brand videos for AI startups that turn complex tech into something instantly understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tallyhq.com', company: 'Tally', body: `Hey,\n\nTally is automating accounting and audit with AI — a product that CFOs need to see, not just read about. I make short motion graphic brand videos for AI fintech startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sammylabs.com', company: 'Sammy Labs', body: `Hey,\n\nSammy Labs caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@instinct-space.com', company: 'Instinct', body: `Hey,\n\nInstinct is building something ambitious. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mercura.ai', company: 'Mercura', body: `Hey,\n\nMercura is doing interesting work in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tamlabs.ai', company: 'TamLabs', body: `Hey,\n\nTamLabs is building in AI. I make short motion graphic brand videos for AI startups that turn complex products into something instantly understandable.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@runcopycat.com', company: 'CopyCat', body: `Hey,\n\nCopyCat is doing AI code migration — a product developers love but that needs a clear visual story for decision-makers. I make short motion graphic brand videos for AI dev-tools startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@paratushealth.com', company: 'Paratus Health', body: `Hey,\n\nParatus Health is building AI for healthcare — a space where trust and clarity matter as much as the product itself. I make short motion graphic brand videos for health-tech startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tensorpool.dev', company: 'TensorPool', body: `Hey,\n\nTensorPool is building distributed GPU compute — a technical product that benefits hugely from a clean visual explainer. I make short motion graphic brand videos for AI infrastructure startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@dalus.io', company: 'Dalus', body: `Hey,\n\nDalus caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@rebolt.ai', company: 'Rebolt', body: `Hey,\n\nRebolt is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@spott.io', company: 'Spott', body: `Hey,\n\nSpott is doing interesting work. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@withwoz.com', company: 'Woz', body: `Hey,\n\nWoz caught my eye. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@proception.ai', company: 'Proception', body: `Hey,\n\nProception is building AI perception technology — a product that's inherently visual and perfect for a motion graphic demo. I make short brand videos for AI startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@joindemeter.com', company: 'Demeter', body: `Hey,\n\nDemeter is building in AI for agriculture — a space with a great visual story waiting to be told. I make short motion graphic brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@wild-card.ai', company: 'Wildcard', body: `Hey,\n\nWildcard is doing interesting work in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@permitify.com', company: 'Permitify', body: `Hey,\n\nPermitify is building AI for permits and compliance — one of the most frustrating processes to go through, but a great problem to visualize being solved. I make short motion graphic brand videos for AI startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@reditus.space', company: 'Reditus Space', body: `Hey,\n\nReditus Space is building in the new space economy — a genuinely exciting product category. I make short motion graphic brand videos for deep tech startups that make ambitious tech accessible.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@startpinch.com', company: 'Pinch', body: `Hey,\n\nPinch caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@retrofit.shop', company: 'Retrofit', body: `Hey,\n\nRetrofit is building something interesting. I make short motion graphic brand videos for AI startups that turn what you do into something instantly clear and shareable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@archon.inc', company: 'Archon', body: `Hey,\n\nArchon is doing interesting work in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mastra.ai', company: 'Mastra', body: `Hey,\n\nMastra is building a TypeScript AI framework — a developer tool that needs a clean visual story to reach the right audience fast. I make short motion graphic brand videos for AI dev-tools startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@afterquery.com', company: 'AfterQuery', body: `Hey,\n\nAfterQuery is building in AI data. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@fuse.ai', company: 'Fuse AI', body: `Hey,\n\nFuse AI caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@miyagilabs.ai', company: 'Miyagi Labs', body: `Hey,\n\nMiyagi Labs is building in AI — a space where showing beats telling every time. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@triplezip.ai', company: 'TripleZip', body: `Hey,\n\nTripleZip is doing interesting work. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usepeppr.ai', company: 'Peppr', body: `Hey,\n\nPeppr is building AI for restaurants — an industry that's very visual and where a great brand video can really stand out. I make short motion graphic brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sennu.ai', company: 'Sennu AI', body: `Hey,\n\nSennu AI caught my eye. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@orbitalops.tech', company: 'Orbital Operations', body: `Hey,\n\nOrbital Operations is building in space tech — one of the most visually compelling product categories out there. I make short motion graphic brand videos for deep tech startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usemesh.com', company: 'Mesh', body: `Hey,\n\nMesh is building in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@outlit.ai', company: 'Outlit', body: `Hey,\n\nOutlit is doing interesting work in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@harperinsure.com', company: 'Harper', body: `Hey,\n\nHarper is building AI for insurance — a product that needs to build trust fast. I make short motion graphic brand videos for insurtech startups that make the value instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@calltree.ai', company: 'Calltree AI', body: `Hey,\n\nCalltree AI is building AI for call centers — a product that's perfect for a before/after motion graphic explainer. I make short brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@nitrode.com', company: 'Nitrode', body: `Hey,\n\nNitrode caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@gokarsa.com', company: 'Karsa', body: `Hey,\n\nKarsa is building in AI. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@exla.ai', company: 'Exla', body: `Hey,\n\nExla is building AI compute resources. I make short motion graphic brand videos for AI infrastructure startups that turn technical products into something instantly clear.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@withriviera.com', company: 'Riviera', body: `Hey,\n\nRiviera caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@vovana.com', company: 'Vovana', body: `Hey,\n\nVovana is doing interesting work in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@agentin.ai', company: 'Agentin AI', body: `Hey,\n\nAgentin AI is building in the AI agents space — one of the hottest and hardest-to-explain categories right now. I make short motion graphic explainers for AI startups that make agents understandable.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@rejot.dev', company: 'ReJot', body: `Hey,\n\nReJot is building developer tooling. I make short motion graphic brand videos for AI and dev-tools startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@generaltrajectory.com', company: 'General Trajectory', body: `Hey,\n\nGeneral Trajectory is doing interesting work. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@solidroad.com', company: 'SolidRoad', body: `Hey,\n\nSolidRoad is building AI for sales coaching — a product that coaches need to see working to believe. I make short motion graphic brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@trytrata.com', company: 'Trata', body: `Hey,\n\nTrata caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sophris.ai', company: 'Sophris', body: `Hey,\n\nSophris is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@lucidic.ai', company: 'Lucidic AI', body: `Hey,\n\nLucidic AI is building observability for AI agents — a technical product that benefits from a clean visual story. I make short motion graphic brand videos for AI infrastructure startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mundoai.world', company: 'Mundo AI', body: `Hey,\n\nMundo AI is doing interesting work in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@athenahq.ai', company: 'AthenaHQ', body: `Hey,\n\nAthenaHQ is building in AI. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@lopus.ai', company: 'Lopus AI', body: `Hey,\n\nLopus AI caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@joincenote.com', company: 'Cenote', body: `Hey,\n\nCenote is doing interesting work. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@harbera.com', company: 'Harbera', body: `Hey,\n\nHarbera caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@augento.ai', company: 'Augento', body: `Hey,\n\nAugento is building in AI agents. I make short motion graphic brand videos for AI startups that make abstract products click instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@galevisa.com', company: 'Gale', body: `Hey,\n\nGale is building AI for visa and immigration — a complex process that's perfect for a clear visual walkthrough. I make short motion graphic brand videos for AI startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@pave-robotics.com', company: 'Pave Robotics', body: `Hey,\n\nPave Robotics is building autonomous construction equipment — hardware that looks incredible in motion. I make short motion graphic brand videos for deep tech startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@fromolive.com', company: 'Olive', body: `Hey,\n\nOlive caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@hud.so', company: 'HUD', body: `Hey,\n\nHUD is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@cuckoo.so', company: 'Cuckoo Labs', body: `Hey,\n\nCuckoo Labs is building real-time AI translation for global teams — a product where the before/after is instantly compelling. I make short motion graphic brand videos for AI startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mecha-health.ai', company: 'Mecha Health', body: `Hey,\n\nMecha Health is building AI for healthcare operations. I make short motion graphic brand videos for health-tech startups that make complex workflows instantly clear.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@gradewiz.ai', company: 'GradeWiz', body: `Hey,\n\nGradeWiz is building AI for education — a product that teachers and admins need to see to understand. I make short motion graphic brand videos for ed-tech AI startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@gethealthkey.com', company: 'HealthKey', body: `Hey,\n\nHealthKey caught my eye. I make short motion graphic brand videos for health-tech startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mosaicco.com', company: 'Mosaic', body: `Hey,\n\nMosaic is building in AI. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@zeroentropy.dev', company: 'ZeroEntropy', body: `Hey,\n\nZeroEntropy is building AI search — a product that's highly technical but where the speed and accuracy story is visually compelling. I make short motion graphic brand videos for AI startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@cardamon.ai', company: 'Cardamon', body: `Hey,\n\nCardamon caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tryamby.com', company: 'Amby Health', body: `Hey,\n\nAmby Health is building AI for healthcare. I make short motion graphic brand videos for health-tech startups that build trust and clarity fast.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@carecycle.ai', company: 'careCycle', body: `Hey,\n\ncareCycle is building AI voice teams for Medicare — a product where trust and clarity are everything. I make short motion graphic brand videos for health-tech AI startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@heysift.com', company: 'Sift Dev', body: `Hey,\n\nSift Dev is building in AI for developers. I make short motion graphic brand videos for AI dev-tools startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@maive.ai', company: 'Maive', body: `Hey,\n\nMaive caught my eye. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@caseflood.ai', company: 'Caseflood', body: `Hey,\n\nCaseflood is replacing law firm admin with AI agents — a product where showing the before/after is incredibly powerful. I make short motion graphic brand videos for legal-tech AI startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@trytejas.ai', company: 'Tejas AI', body: `Hey,\n\nTejas AI is doing interesting work. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usevora.ai', company: 'Vora AI', body: `Hey,\n\nVora AI caught my eye. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@maritimefusion.com', company: 'Maritime Fusion', body: `Hey,\n\nMaritime Fusion is building in deep tech. I make short motion graphic brand videos for deep tech startups that make ambitious technology accessible to a broader audience.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@a1base.com', company: 'A1Base', body: `Hey,\n\nA1Base is building AI infrastructure. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@verbiflow.com', company: 'Verbiflow', body: `Hey,\n\nVerbiflow is doing interesting work in AI language. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@toothy.ai', company: 'Toothy AI', body: `Hey,\n\nToothy AI caught my eye. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@rocketable.com', company: 'Rocketable', body: `Hey,\n\nRocketable is building something ambitious. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sublingual.ai', company: 'Sublingual', body: `Hey,\n\nSublingual is doing interesting work in AI biotech. I make short motion graphic brand videos for deep tech startups that make complex science instantly accessible.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@contrario.ai', company: 'Contrario', body: `Hey,\n\nContrario caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@ovlo.ai', company: 'Ovlo', body: `Hey,\n\nOvlo is building in AI. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@trytruffle.ai', company: 'Truffle AI', body: `Hey,\n\nTruffle AI is building AI-powered browser automation — a product that's inherently visual and perfect for a short demo explainer. I make motion graphic brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@superglue.ai', company: 'superglue', body: `Hey,\n\nsuperglue is building AI data integration. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@closure-intel.com', company: 'Closure', body: `Hey,\n\nClosure caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@gopromptless.ai', company: 'Promptless', body: `Hey,\n\nPromptless is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@scoutforschools.com', company: 'Scout', body: `Hey,\n\nScout is building AI for schools. I make short motion graphic brand videos for ed-tech startups that make the value instantly clear to administrators and teachers.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@subtrace.dev', company: 'Subtrace', body: `Hey,\n\nSubtrace is building AI-powered network observability — a technical product where a clean visual explainer can do a lot of heavy lifting. I make short motion graphic brand videos for AI dev-tools startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@vocalityhealth.com', company: 'Vocality Health', body: `Hey,\n\nVocality Health caught my eye. I make short motion graphic brand videos for health-tech startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@astroenergy.ai', company: 'Astro', body: `Hey,\n\nAstro is building AI for energy. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@dollyglot.com', company: 'Dollyglot', body: `Hey,\n\nDollyglot is building AI translation. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@stampmail.ai', company: 'Stamp', body: `Hey,\n\nStamp caught my eye. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@guse.io', company: 'Guse', body: `Hey,\n\nGuse is doing interesting work. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@subimage.io', company: 'SubImage', body: `Hey,\n\nSubImage caught my eye. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@nextbyte.ai', company: 'NextByte', body: `Hey,\n\nNextByte is building in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@leapingai.com', company: 'Leaping AI', body: `Hey,\n\nLeaping AI caught my eye. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@bild.ai', company: 'Bild AI', body: `Hey,\n\nBild AI is building in AI for construction — a huge industry with a great visual story. I make short motion graphic brand videos for AI startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
];

async function runBatch() {
  const stats = getDailyStats();
  if (stats.remaining === 0) {
    console.log('Daily limit already reached. Try again tomorrow.');
    process.exit(0);
  }

  const toSend = outreach.slice(0, stats.remaining);
  console.log(`Sending ${toSend.length} emails (${stats.remaining} remaining today)...`);

  let sent = 0;
  let failed = 0;

  for (const email of toSend) {
    try {
      await sendEmail({
        to: email.to,
        subject: `Quick brand video idea for ${email.company}`,
        body: email.body,
      });
      console.log(`✓ ${email.company} → ${email.to}`);
      sent++;
    } catch (err) {
      console.error(`✗ ${email.company} → ${email.to}: ${err.message}`);
      failed++;
    }
    await new Promise(r => setTimeout(r, 2000));
  }

  console.log(`\nDone. ${sent} sent, ${failed} failed.`);
}

runBatch();
