import { sendEmail, getDailyStats } from '../src/mailer.js';

const outreach = [
  { to: 'kabir@inviscidai.com', company: 'Inviscid', body: `Hey,\n\nInviscid is doing interesting work in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@travoai.com', company: 'Travo', body: `Hey,\n\nTravo is building something in real estate AI — a space that's hard to explain but easy to show. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usebidflow.com', company: 'Bidflow', body: `Hey,\n\nBidflow is working on something in the AI space. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@polymathlabs.ai', company: 'Polymath', body: `Hey,\n\nPolymath is building in AI — a category where showing beats telling every time. I make short motion graphic brand videos for AI startups that turn complex tech into something instantly understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@jinba.io', company: 'Jinba', body: `Hey,\n\nJinba caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@envariant.ai', company: 'Envariant', body: `Hey,\n\nEnvariant is doing interesting work in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@lance.live', company: 'Lance', body: `Hey,\n\nLance is building something compelling. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tepali.com', company: 'Tepali', body: `Hey,\n\nTepali is working on something in AI. I make short motion graphic brand videos that turn what you do into something instantly clear and shareable.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@fern.bot', company: 'Fern', body: `Hey,\n\nFern is building developer tooling — a product that's hard to explain in text but perfect for a clean motion graphic explainer. I make short brand videos for AI and dev-tools startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tryclam.com', company: 'Clam', body: `Hey,\n\nClam is working in AI security. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usecarson.com', company: 'Carson', body: `Hey,\n\nCarson is building something in AI. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@lucenthq.com', company: 'Lucent', body: `Hey,\n\nLucent is doing interesting work. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@agenticfabriq.com', company: 'Agentic Fabriq', body: `Hey,\n\nAgentic Fabriq is building in the AI agents space — one of the hottest and hardest-to-explain categories right now. I make short motion graphic explainers for AI startups that make agents understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@ressl.ai', company: 'Ressl', body: `Hey,\n\nRessl caught my eye. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usecrow.ai', company: 'Crow', body: `Hey,\n\nCrow is building AI for commercial real estate — a space where a sharp visual explainer can really differentiate you. I make short motion graphic brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@revion.inc', company: 'Revion', body: `Hey,\n\nRevion is doing interesting work. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@overshoot.ai', company: 'Overshoot', body: `Hey,\n\nOvershoot is building in AI vision — a product that's inherently visual and perfect for a motion graphic explainer. I make short brand videos for AI startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@byteport.com', company: 'Byteport', body: `Hey,\n\nByteport is working on infrastructure AI. I make short motion graphic brand videos for AI startups that turn technical products into something instantly understandable.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@ramain.ai', company: 'RamAIn', body: `Hey,\n\nRamAIn is building AI for computer use — a genuinely hard concept to explain. I make short motion graphic brand videos for AI startups that make abstract products click instantly.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@perfectly.so', company: 'Perfectly', body: `Hey,\n\nPerfectly caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@samora.ai', company: 'Samora AI', body: `Hey,\n\nSamora AI is doing interesting work. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sentrial.com', company: 'Sentrial', body: `Hey,\n\nSentrial is building AI observability — a product that's hard to explain in text but great as a visual explainer. I make short motion graphic brand videos for AI infrastructure startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@shortkit.dev', company: 'Shortkit', body: `Hey,\n\nShortkit is working in dev tools. I make short motion graphic brand videos for AI and dev-tools startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@runcanary.ai', company: 'Canary', body: `Hey,\n\nCanary is building in AI. I make short motion graphic brand videos for AI startups that make complex products instantly understandable.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usemoda.ai', company: 'Moda', body: `Hey,\n\nModa caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@incidentfox.ai', company: 'IncidentFox', body: `Hey,\n\nIncidentFox is building AI for incident management — a product that engineers love but that's hard to sell to leadership without a clear visual story. I make short motion graphic brand videos for AI startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tensol.ai', company: 'Tensol', body: `Hey,\n\nTensol is doing interesting work in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@terminaluse.com', company: 'Terminal Use', body: `Hey,\n\nTerminal Use is building something in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@luel.ai', company: 'Luel', body: `Hey,\n\nLuel caught my eye. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@compresr.ai', company: 'Compresr', body: `Hey,\n\nCompresr is working in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@cumuluslabs.io', company: 'Cumulus Labs', body: `Hey,\n\nCumulus Labs is building in AI infrastructure. I make short motion graphic brand videos for AI startups that turn technical products into something instantly understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@axisanalysis.com', company: 'Axis', body: `Hey,\n\nAxis is doing AI for commodities — a complex space where a sharp visual explainer can really set you apart. I make short motion graphic brand videos for AI startups.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@fenrock.ai', company: 'Fenrock', body: `Hey,\n\nFenrock is building AI for banking back office — a product that's hard to explain but critical to show. I make short motion graphic brand videos for AI fintech startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@pollinate.tech', company: 'Pollinate', body: `Hey,\n\nPollinate caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@burthq.com', company: 'Burt', body: `Hey,\n\nBurt is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tryasimov.ai', company: 'Asimov', body: `Hey,\n\nAsimov is doing interesting work in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@celltype.com', company: 'CellType', body: `Hey,\n\nCellType is building a biological world model — one of the most ambitious and hardest-to-explain products out there. I make short motion graphic brand videos that make complex science instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@beaconhealth.ai', company: 'Beacon Health', body: `Hey,\n\nBeacon Health is building AI for healthcare. I make short motion graphic brand videos for AI health startups — clean explainers that build trust and make your value instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@docurahealth.com', company: 'Docura Health', body: `Hey,\n\nDocura Health is working in AI healthcare. I make short motion graphic brand videos for AI health startups that make your product instantly clear to providers and payers.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@strandai.com', company: 'Strand AI', body: `Hey,\n\nStrand AI caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mangomedical.io', company: 'Mango Medical', body: `Hey,\n\nMango Medical is building in AI healthcare. I make short motion graphic brand videos for AI health startups that build trust and make your value instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tryremy.ai', company: 'Remy AI', body: `Hey,\n\nRemy AI is doing interesting work. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@kytentech.com', company: 'Kyten Technologies', body: `Hey,\n\nKyten Technologies is building something compelling. I make short motion graphic brand videos for AI and deep tech startups that make technical products instantly understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@fullseam.com', company: 'FullSeam', body: `Hey,\n\nFullSeam caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@getbalance.ai', company: 'Balance', body: `Hey,\n\nBalance is building in AI fintech. I make short motion graphic brand videos for AI financial startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@endclose.com', company: 'End Close', body: `Hey,\n\nEnd Close is building in AI finance. I make short motion graphic brand videos for AI fintech startups that make complex workflows instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tryq2q.com', company: 'Q2Q', body: `Hey,\n\nQ2Q caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@wideframe.com', company: 'Wideframe', body: `Hey,\n\nWideframe is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@usereframe.ai', company: 'Reframe', body: `Hey,\n\nReframe is automating hardware procurement — a painfully manual process that's perfect to visualize. I make short motion graphic brand videos for AI startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sitefire.ai', company: 'Sitefire', body: `Hey,\n\nSitefire caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mantisbiotech.com', company: 'Mantis', body: `Hey,\n\nMantis is building cognitive intelligence for enterprises — a big claim that a sharp visual explainer can make instantly believable. I make short motion graphic brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@codewisp.ai', company: 'CodeWisp', body: `Hey,\n\nCodeWisp is working in AI for code. I make short motion graphic brand videos for AI dev-tools startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@corvera.ai', company: 'Corvera', body: `Hey,\n\nCorvera caught my eye. I make short motion graphic brand videos for AI startups that make complex products pop instantly.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@eigenpal.com', company: 'EigenPal', body: `Hey,\n\nEigenPal is building in AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@beyondreachlabs.com', company: 'Beyond Reach Labs', body: `Hey,\n\nBeyond Reach Labs is building in energy and power — a space where showing what you do is far more powerful than telling. I make short motion graphic brand videos for deep tech startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@cofia.ai', company: 'Cofia', body: `Hey,\n\nCofia caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tryrobby.com', company: 'Robby', body: `Hey,\n\nRobby is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@robodock.tech', company: 'RoboDock', body: `Hey,\n\nRoboDock is working in robotics — a space where a clean visual explainer can make the difference between getting a meeting or not. I make short motion graphic brand videos for robotics startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@voxelenergy.com', company: 'Voxel Energy', body: `Hey,\n\nVoxel Energy is building in clean energy. I make short motion graphic brand videos for deep tech startups — clean explainers that make complex technology instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@general.legal', company: 'General Legal', body: `Hey,\n\nGeneral Legal is building in AI for law — a space where trust and clarity are everything. I make short motion graphic brand videos for AI legal startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@legalos.ai', company: 'LegalOS', body: `Hey,\n\nLegalOS is working in AI legal tech. I make short motion graphic brand videos for AI legal startups — clean explainers that build trust and make your value instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@ashr.io', company: 'Ashr', body: `Hey,\n\nAshr caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@resonate.audio', company: 'Resonate', body: `Hey,\n\nResonate is building in audio AI — a product that's inherently sensory and perfect for a motion graphic explainer. I make short brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@hlaboratories.com', company: 'HLabs', body: `Hey,\n\nHLabs is building robotics — a space where showing what your robots do is far more compelling than describing it. I make short motion graphic brand videos for robotics startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@tryoctapulse.com', company: 'OctaPulse', body: `Hey,\n\nOctaPulse caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@verdexai.com', company: 'Verdex', body: `Hey,\n\nVerdex is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@dronetector.com', company: 'DroneTector', body: `Hey,\n\nDroneTector is working in drone detection — a product that's inherently visual and perfect for a motion graphic explainer. I make short brand videos for deep tech startups.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@lexius.ai', company: 'Lexius', body: `Hey,\n\nLexius is building in AI legal. I make short motion graphic brand videos for AI legal startups — clean explainers that make your value instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@mousecat.ai', company: 'MouseCat', body: `Hey,\n\nMouseCat caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sequencemkts.com', company: 'Sequence Markets', body: `Hey,\n\nSequence Markets is building in AI for financial markets. I make short motion graphic brand videos for AI fintech startups — clean explainers that make complex products instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sonarly.com', company: 'Sonarly', body: `Hey,\n\nSonarly is doing interesting work in audio/AI. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@terranox.ai', company: 'Terranox AI', body: `Hey,\n\nTerranox AI caught my eye. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@buttoncomputer.com', company: 'Button Computer', body: `Hey,\n\nButton Computer is building in hardware/AI. I make short motion graphic brand videos for deep tech startups — clean explainers that make technical products instantly understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@paxhistoria.co', company: 'Pax Historia', body: `Hey,\n\nPax Historia is building something in AI and history — a genuinely creative product. I make short motion graphic brand videos for AI startups that make unique products instantly compelling.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@catchbackcards.com', company: 'CatchBack', body: `Hey,\n\nCatchBack is reimagining trading cards with guaranteed buyback — a novel concept that a sharp motion graphic can make instantly clear. I make short brand videos for consumer startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@seeing-systems.com', company: 'Seeing Systems', body: `Hey,\n\nSeeing Systems is building in AI vision. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@origami-robotics.com', company: 'Origami Robotics', body: `Hey,\n\nOrigami Robotics is building robots — a product that practically sells itself visually. I make short motion graphic brand videos for robotics startups that show what you're building in a way that excites people.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@generalastro.com', company: 'General Astronautics', body: `Hey,\n\nGeneral Astronautics is doing something ambitious in space. I make short motion graphic brand videos for deep tech startups — clean explainers that make your vision instantly compelling.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@axionorbital.space', company: 'AxionOrbital', body: `Hey,\n\nAxionOrbital is building in space tech. I make short motion graphic brand videos for deep tech and space startups — clean explainers that make ambitious visions instantly clear.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@grazemate.com', company: 'GrazeMate', body: `Hey,\n\nGrazeMate is working in agtech. I make short motion graphic brand videos for startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@spotpay.ai', company: 'SpotPay', body: `Hey,\n\nSpotPay is building in AI payments. I make short motion graphic brand videos for AI fintech startups — clean explainers that make your value instantly clear.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@caretta.so', company: 'Caretta', body: `Hey,\n\nCaretta caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@chasi.ai', company: 'Chasi', body: `Hey,\n\nChasi is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@valgo.ai', company: 'Valgo', body: `Hey,\n\nValgo caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@10xscience.com', company: '10x Science', body: `Hey,\n\n10x Science is building something ambitious in biotech/science. I make short motion graphic brand videos that make complex science instantly clear and compelling.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@zymbly.com', company: 'Zymbly', body: `Hey,\n\nZymbly caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@bubblelab.ai', company: 'Bubble Lab', body: `Hey,\n\nBubble Lab is building in AI. I make short motion graphic brand videos for AI startups that make your product pop instantly.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@corelayer.com', company: 'Corelayer', body: `Hey,\n\nCorelayer is working in AI infrastructure. I make short motion graphic brand videos for AI infrastructure startups — clean explainers that make technical products instantly understandable.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@sparkles.dev', company: 'Sparkles', body: `Hey,\n\nSparkles is building in AI dev tools. I make short motion graphic brand videos for AI and dev-tools startups — clean explainers that make your value clear in under 30 seconds.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@protent.ai', company: 'Protent', body: `Hey,\n\nProtent is working in AI for law enforcement — a trust-heavy space where a sharp visual story matters a lot. I make short motion graphic brand videos for AI startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@fed10.ai', company: 'Fed10', body: `Hey,\n\nFed10 caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@vectorlegal.com', company: 'Vector Legal', body: `Hey,\n\nVector Legal is building in AI legal tech. I make short motion graphic brand videos for AI legal startups — clean explainers that make your value instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@emdash.sh', company: 'Emdash', body: `Hey,\n\nEmdash caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@skillsync.wiki', company: 'Skillsync', body: `Hey,\n\nSkillsync is building in AI for skills. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@o11.ai', company: 'o11', body: `Hey,\n\no11 caught my eye. I make short motion graphic brand videos for AI startups that make complex products instantly clear.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@overdrive.health', company: 'Overdrive Health', body: `Hey,\n\nOverdrive Health is working in AI medical billing — a necessary but complex product that a sharp visual explainer can make instantly compelling. I make short motion graphic brand videos for AI health startups.\n\nInterested?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@zatanna.ai', company: 'Zatanna', body: `Hey,\n\nZatanna caught my eye. I make short motion graphic brand videos for AI startups — clean explainers that make your value clear in under 30 seconds.\n\nOpen to a quick conversation?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
  { to: 'hello@pranadoc.com', company: 'Prana', body: `Hey,\n\nPrana is building an AI doctor — one of the most ambitious products in healthcare AI. I make short motion graphic brand videos that make bold health AI products instantly clear and trustworthy.\n\nWorth a quick chat?\n\n— Jay\njayrx.net\njayrx16@gmail.com` },
];

async function runBatch() {
  const stats = getDailyStats();
  console.log(`Daily limit: ${stats.sent} sent, ${stats.remaining} remaining today`);

  if (stats.remaining === 0) {
    console.log('Daily limit already reached. Try again tomorrow.');
    process.exit(0);
  }

  let sent = 0;
  let failed = 0;
  const toSend = outreach.slice(0, stats.remaining);

  for (const email of toSend) {
    try {
      await sendEmail({
        to: email.to,
        subject: `Quick brand video idea for ${email.company}`,
        body: email.body,
      });
      console.log(`✓ Sent to ${email.to}`);
      sent++;
    } catch (err) {
      console.error(`✗ Failed: ${email.to} — ${err.message}`);
      failed++;
    }
    await new Promise(r => setTimeout(r, 2000));
  }

  console.log(`\n✓ ${sent} sent | ✗ ${failed} failed`);
}

runBatch();
